app/livewith/utilities/dinner/urls.py
from django.conf.urls.defaults import patterns
from django.views.generic.simple import redirect_to

urlpatterns = patterns(                    
    'livewith.utilities.dinner.views',  
    (r'house_settings_handler$', 'house_settings_handler'),   
    (r'pollhandler$', 'dinner_poll_handler'), 
    (r'deactivate$', 'deactivate'), 
    (r'activate$', 'activate'),           
    (r'$', redirect_to, {'url': '/lw/settings/#utilities'}), # redirect to settings for utilities
    )

app/livewith/utilities/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.conf.urls.defaults import patterns
from django.views.generic.simple import redirect_to

urlpatterns = patterns('',
    (r'crontab/', 'run_utility_crons'),
    (r'dinner/', include('livewith.utilities.dinner.urls')),
    (r'$', redirect_to, {'url': '/lw/settings/#utilities'}), # redirect to settings for utilities
)

app/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import django.views.generic.simple
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^djsite/', include('djsite.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    #helloworld stie URLs
    (r'^$', 'livewith.views.index'),
    (r'^pages/(?P<page_name>\w+)/$', 'livewith.views.pageview'),
    
    (r'^lw/', include('livewith.urls')),
    (r'^analytics/', include('livewith.analytics.urls')),
)

# static content serving -- for local dev only
if settings.DEBUG:
	urlpatterns += patterns('',
	    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'C:/livewithus/site_media', 'show_indexes': True}), 
	)

app/livewith/utilities/models.py
from django.db import models
from livewith.models import House, HMCreator, Person
from djsite.polymorphic.models import DowncastMetaclass
import djsite.settings

class HMUtility(HMCreator):
	"Base class for Utilities. All utilities must extend this model."
	
	name = models.CharField(max_length=32)
	avatar = models.ImageField(upload_to="uploads/utilities/", blank = True)
	path = models.CharField(max_length=255, null=True, blank=True) # optional path, to be used in the case of 3rd party utilities hosted off-server
	summary_template = models.CharField(max_length=200)

	def get_avatar(self):
		if self.avatar:
			return '/site_media/%s' % self.avatar
		else:
			return djsite.settings.DEFAULT_AVATAR

	def get_sm_avatar(self):
		if self.avatar:
			return '/site_media/%s' % self.avatar
		else:
			return djsite.settings.DEFAULT_AVATAR

	def __unicode__(self):
		return self.name
	
		
class UtilityHouseSettings(models.Model):
	"""
	Base class defining House-specific settings for Utilities.
	Extensions of this class should define utility settings specific to a house.
	"""
	house = models.ForeignKey(House)
	utility = models.ForeignKey(HMUtility)
	active = models.BooleanField()
	template = models.CharField(max_length=200)
	
	__metaclass__ = DowncastMetaclass
	
class UtilityPersonSettings(models.Model):
	"""
	Base class defining User/Person-specific settings for Utilities.
	Extensions of this class should define utility settings specific to a user.
	"""
	person = models.ForeignKey(Person)
	utility = models.ForeignKey(HMUtility)
	active = models.BooleanField()
	template = models.CharField(max_length=200)
	
	__metaclass__ = DowncastMetaclass
	
	
	

templates/alpha/chatter/base_poll.html
{% load image_sizing %}
{% load humanizetime %}

<img src="{{chat.get_avatar}}" width="30" height="30" />
<b>{{chat.text}}</b><br />
<span class="chat-time">{{chat.timeCreated|naturalTimeDifference}}</span>
{% ifequal chat.creator.downcast person %}[<a href="/lw/{{house.pk}}/chatter/{{chat.pk}}/delete/">x</a>]{% endifequal %}
<table>
<tr>
<td></td>
{% for o in chat.option_set.all %}
<td>{{o.option_text}}</td>
{% endfor %}
</tr>
{% for member in house.getHouseMembers %}
	{% ifnotequal member person %}
	<tr>
		<td>
		<img src="{{member.get_sm_avatar}}" width="20" height="20" />
		</td>
		{% for o in chat.option_set_with_people %}
		<td><input type="checkbox" name="poll_choice" value="{{o.pk}}" {% if member in o.list %}checked {% endif %}disabled /></td>
		{% endfor %}
	</tr>
	{% endifnotequal %}
{% endfor %}
<tr>
	<td>
		<img src="{{person.get_sm_avatar}}" width="20" height="20" />
	</td>
<form action="/lw/pollhandler/" method="post">
	<input type="hidden" value="{{chat.pk}}" name="poll_id" />
	<input type="hidden" value={{house.pk}} name="house_id" id="id_house" />
	{% for o in chat.option_set_with_people %}
		<td>
		<input type="checkbox" name="poll_choice" value="{{o.pk}}" {% if person in o.list %}checked {% endif %} />
		</td>
	{% endfor %}
</tr>
</table>
<input type="submit" value="Vote" />
</form>

templates/alpha/chatter/chat.html
{% load humanizetime %}
{% if chat.get_template_url %}{# if there is a special rendering function, display that instead #}
	{% include chat.get_template_url %}
{% else %}{# if not, display chatters as they usually are done #}
	{% if chat.publicly_editable %}
	<form action="/lw/savewikihandler/" method="post">
		<img src="{{chat.get_avatar}}" width="30" height="30" />
		Wiki post:
		<br /> 
		<textarea cols="60" rows="2" name="text">{{chat.text}}</textarea><br />
		<input type="hidden" value="{{chat.pk}}" name="chat" id="id_chat" />
    	<input type="hidden" value="{{house.pk}}" name="house" id="id_house" />
		<input type="submit" value="Save" />
	</form>
	{% else %}
	<div class="chat-item">
		<img class="chat-img" src="{{chat.get_avatar}}" width="30" height="30" />
		{{chat.text|urlize|linebreaks}}
		<span class="chat-time">{{chat.timeCreated|naturalTimeDifference}}</span>
		{% ifequal chat.creator.downcast person %}[<a href="/lw/{{house.pk}}/chatter/{{chat.pk}}/delete/">x</a>]{% endifequal %}
		{% if not chat.parent %}{# only allow stickying base chats #}
			{% if chat.sticky %}
			[<a href="/lw/{{house.pk}}/chatter/{{chat.pk}}/unstick/">unstick</a>]
			{% else %}
			[<a href="/lw/{{house.pk}}/chatter/{{chat.pk}}/stick/">stick</a>]
			{% endif %}
		{%endif%}
	</div>
	{% endif %}
{% endif %}

templates/alpha/chatter/chat_form.html
{% if chat %}{# FOR REPLIES #}
<form action="/lw/chathandler/" method="post" class="chat-reply-form" id="chat-reply-form-{{chat.pk}}">
	<img class="chat-img" src="{{person.get_sm_avatar}}" width="20" height="20" />
    {{ form.text }}<br />
    {% if chat %}<input type="hidden" value="{{chat.pk}}" name="parent" id="id_parent" />{% endif %}
    <input type="hidden" value="{{house.pk}}" name="house" id="id_house" />
    <div class="chat-buttons">
	<input type="submit" value="Reply" />
	</div>
</form>
{% else %}{# FOR TOP-LEVEL CHATS #}
<form action="/lw/chathandler/" method="post" class="chat-form" id="new-chat-form">
	<img class="chat-img" src="{{person.get_avatar}}" width="30" height="30" />
    {{ form.text }}<br />
	<input type="hidden" value="{{chat.pk}}" name="parent" id="id_parent" />
    <input type="hidden" value="{{house.pk}}" name="house" id="id_house" />
    <div class="chat-form-buttons-area" id="new-chat-form-buttons">
    <div class="chat-form-buttons-left">
    	Advanced:
    	<a id="new-chat-form-poll-button"><img src="/site_media/img/led-icons/chart_bar.png" title="Create a poll"  /></a>
    </div>
    <div class="chat-form-buttons">
	<input type="submit" value="Post" />
	</div>
	</div>
	<div class="chat-form-poll-area" id="new-chat-form-poll">
		One poll option per line, first line is the poll question.<br />
		<input type="hidden" name="as_poll" value="false" />
		Poll type: <select name="poll-type">
			<option>Excellence</option>
			{%comment%}<option>Single Vote</option>{%endcomment%}
		</select> <a href="/lw/faq/#poll-types">what is this?</a>
		<div class="chat-form-buttons">
		<input type="button" id="new-chat-cancel-poll" value="Cancel" /></a><input type="submit" value="Create Poll">
		</div>
	</div>
</form>
{% endif %}

templates/alpha/chatter/more_chats.html
{% load humanizetime %}
{% for chat in chats %}
	{% include "alpha/chatter/chat.html" %}
	<div class="chat-child">
		{% for chat in chat.child_set.all %}
			{% include "alpha/chatter/chat.html" %}
		{% endfor %}
		{% include "alpha/chatter/chat_form.html" %}
	</div>
{% endfor %}

templates/alpha/chatter/poll_form.html
<form action="/lw/chathandler/" method="post">
    {{ form.text }}<br />
    {{ form.publicly_editable }}Wiki?<br />
    {{ form.sticky }}Sticky?<br />
    <input type="hidden" value={{chat.pk}} name="parent" id="id_parent" />
    <input type="hidden" value={{house.pk}} name="house" id="id_house" />
	{% if chat %}<input type="submit" value="Post Reply" />{% else %}<input type="submit" value="Post Chatter" />{% endif %}
</form>